apiVersion: v1
kind: Service
metadata:
  name: phone-socket
  labels:
    app: phone-socket
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: phone-socket
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-socket
  labels:
    app: phone-socket
    version: v1
spec:
  selector:
    matchLabels:
      app: phone-socket
      version: v1
  template:
    metadata:
      labels:
        app: phone-socket
        version: v1
    spec:
      containers:
        - image: oneadm/phone-socket:1.0
          imagePullPolicy: Always
          name: phone-socket
          command: [ "/bin/sh", "-c", "env" ]
          envFrom:
            - configMapRef:
                name: java-configmap
            - configMapRef:
                name: phone-socket
          command: ["java", "-Dspring.profiles.active=prod", "-jar", "app.jar"]
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phone-socket
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - secretName: phonesocket-tls
      hosts:
        - phonesocket.xckjj.com
  rules:
    - host: phonesocket.xckjj.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: phone-socket
                port:
                  number: 80
